App layout overhaul
projecttacoma/fqm-testify pull request #34
Opened 2022-08-30 17:51 UTC by mgramigna

Draft for now, review #31 and #33 first

# Summary

## New Behavior

## Code Changes

# Testing Guidance

2022-09-01 18:35 UTC, elsaperelli reviewed
The app looks amazing and the renaming and restructuring was really necessary. Just a few comments and questions but looks great!!!

2022-09-01 19:50 UTC, sarahmcdougall requested changes
Aside from in-line comments, here are a few thoughts that came up while reviewing (that don’t necessarily require action but I thought I’d include them here):
* Are there any relevant unit tests that should be added for DataRequirementSelectOption.tsx, PatientInfocard.tsx, or ResourceInfoCard.tsx? I don’t think we have test files for them currently
* I know that we don’t need the SearchBar for searching through resources anymore, so I've been thinking about whether there would be anything (currently implemented or in the future) that should be searchable. I was wondering if it would be helpful for the patients to be searchable by patient name? I’ve been testing with a small number of patients, so I’m not sure how useful it would be, but it’s something we can think about.

2022-09-02 14:28 UTC, mgramigna commented on components/TestCaseEditor.tsx
> +  };
Discussed/resolved through slack

2022-09-02 14:30 UTC, mgramigna commented on components/utils/PatientInfoCard.tsx
> +          style.borderColor = theme.primaryColor;
Yep! I thought `theme.primaryColor` would be that, but turns out we also need `theme.primaryShade` lol

2022-09-02 14:35 UTC, mgramigna commented on util/fhir.ts
>    return `${getPatientNameString(patient)} (DOB: ${patient.birthDate})`;
Addressed in https://github.com/projecttacoma/fqm-testify/pull/34/commits/733b910b37d2833d36152e3c3e1e85863d6595dd

2022-09-02 14:35 UTC, mgramigna commented on components/calculation/MeasureHighlightingPanel.tsx
> +      // TODO: Flip this to true once a new fqm-execution version is released/dependency is updated
Addressed in https://github.com/projecttacoma/fqm-testify/pull/34/commits/733b910b37d2833d36152e3c3e1e85863d6595dd

2022-09-02 14:35 UTC, mgramigna commented on components/TestCaseEditor.tsx
> +  highlightedMarkup: {
Addressed in https://github.com/projecttacoma/fqm-testify/pull/34/commits/733b910b37d2833d36152e3c3e1e85863d6595dd

2022-09-02 14:35 UTC, mgramigna commented on __tests__/components/utils/AppHeader.test.tsx
>  describe('AbacusHeader', () => {
Addressed in https://github.com/projecttacoma/fqm-testify/pull/34/commits/733b910b37d2833d36152e3c3e1e85863d6595dd

2022-09-02 14:35 UTC, mgramigna commented on components/calculation/MeasureHighlightingPanel.tsx
> +      calculateSDEs: false,
Addressed in https://github.com/projecttacoma/fqm-testify/pull/34/commits/733b910b37d2833d36152e3c3e1e85863d6595dd

2022-09-02 14:37 UTC, mgramigna commented on components/resource-creation/ResourcePanel.tsx
> +  const renderDataElements = () => {
Renamed to a better function name in https://github.com/projecttacoma/fqm-testify/pull/34/commits/74c0b32613a3fe42a0d434ec01a8758d6d815c53

2022-09-02 14:37 UTC, mgramigna commented on components/utils/PatientInfoCard.tsx
> +          style.borderColor = theme.primaryColor;
Addressed in https://github.com/projecttacoma/fqm-testify/commit/733b910b37d2833d36152e3c3e1e85863d6595dd

2022-09-02 14:39 UTC, mgramigna commented on components/patient-creation/PatientCreationPanel.tsx
>    const exportAllPatients = () => {
I think that's right. Eventually, this component will only be rendered IFF a measure bundle exists (both name and content)

2022-09-02 15:35 UTC, mgramigna commented on __tests__/components/patient-creation/PatientCreationPanel.test.tsx
> +    const modal = screen.getByTestId('code-editor-modal');
Resolved in https://github.com/projecttacoma/fqm-testify/pull/34/commits/c7422da857fe14f7d9d5a89e4ff03fc845dbce97

2022-09-02 16:50 UTC, elsaperelli approved these changes
Looks good to me!!

2022-09-02 17:42 UTC, sarahmcdougall requested changes

2022-09-02 17:42 UTC, sarahmcdougall commented on __tests__/components/utils/ResourceInfoCard.test.tsx
> +const EXAMPLE_LABEL = 'Colonoscopy (http://example.com/ValueSet/example-vs';
```suggestion
const EXAMPLE_LABEL = 'Colonoscopy (http://example.com/ValueSet/example-vs)';
```

2022-09-02 18:03 UTC, sarahmcdougall approved these changes

2022-09-02 18:05 UTC, merged