README Updates
projecttacoma/fqm-testify pull request #39
Opened 2022-09-13 14:21 UTC by sarahmcdougall

# Summary
Updates the README based on new changes from the design overhaul, adding a custom resource, automatic calculation, etc.

## New Behavior
None

## Code Changes
None

# Testing Guidance
It will be easier to examine the README by opening it as a markdown rather than looking at the code diff. The changes reflect recent PRs (some of which that are not merged), so those should get merged before this README update. Compare README changes to the new features by running `npm run dev` and comparing the new features with the documentation.

2022-09-14 14:49 UTC, hossenlopp reviewed
One small comment on this.

2022-09-14 14:49 UTC, hossenlopp commented on README.md
> +FQM-Testify allows for running measure calculation on a single test case for a given measure. Selecting a patient entry triggers calculation and displays logic highlighting using [the fqm-execution l
They recalculate on change as well, not just new resource creation.

2022-09-14 14:56 UTC, elsaperelli requested changes

2022-09-14 14:56 UTC, elsaperelli commented on README.md
> +FQM-Testify allows the user to create non-Patient FHIR resources after at least one Patient resource is created in or imported to the app. To create a FHIR resource for a test patient, first select t
```suggestion
FQM-Testify allows the user to create non-patient FHIR resources after at least one patient resource is created in or imported to the app. To create a FHIR resource for a test patient, first select the test patient from the left panel. Once selected, FHIR resources can be created from the middle panel in two ways.
```
Not sure if you want these capitalized

2022-09-14 14:56 UTC, elsaperelli commented on README.md
> +FQM-Testify allows for running measure calculation on a single test case for a given measure. Selecting a patient entry triggers calculation and displays logic highlighting using [the fqm-execution l
You can also add in that it automatically generates when the patient is edited or when a test resource is edited! Also if the measure bundle and measurement period are changed.

2022-09-14 19:18 UTC, elsaperelli approved these changes
Great! Way to keep up with the documentation :)

2022-09-16 13:55 UTC, hossenlopp approved these changes

2022-09-16 13:55 UTC, hossenlopp commented
Just needs to be rebased before merging.

2022-09-16 14:15 UTC, merged