Measure report state
projecttacoma/fqm-testify pull request #43
Opened 2022-09-16 18:47 UTC by elsaperelli

- - - 1. 1. # Summary
Before, the measure report for a patient was a property on the patient's state. Now, we can access the measure report for the patient by accessing it by a different state. 

## New Behavior
There is now a new atom for measureReportLookup, so all of the places where calculation takes place were updated to use the new state, but all other behavior remains the same.

## Code Changes
- `measureReportLookup.ts` - creates a new atom for measureReportLookup.
- `MeasureHighlightingPanel.tsx` - Now parses the measure report that is in the measureReportLookup atom.
- `PatientCreationPanel.tsx` - Updated all the places where calculation takes place to use the same state.
- `ResourceDisplay.tsx` - Updated all the places where calculation takes place to use the same state. Also gets rid of the `setTimeout()`.
- `ResourcePanel.tsx` - Updated all the places where calculation takes place to use the same state. 
- `generate-test-cases.ts` - Updated all the places where calculation takes place to use the same state.

# Testing Guidance
1. Run `npm run check` to ensure that all tests still pass and that there are no lint or prettier errors. 
2. Make sure that the measure highlighting changes in the following cases:
- The measurement period is edited
- The measure bundle is changed
- A test case is imported
- A test case is edited
- A test resource is added to a test case
- A test resource is edited
- A test resource is deleted

2022-09-19 17:36 UTC, natjoe4 requested changes
Works great! A couple small fixes. 
 - On patient deletion, we should also delete the MeasureReport associated with that patient
 - MeasureReport field can be removed from patientTestCase state

2022-09-19 19:04 UTC, natjoe4 approved these changes
🎉

2022-09-20 21:17 UTC, hossenlopp requested changes

2022-09-20 21:17 UTC, hossenlopp commented on components/patient-creation/PatientCreationPanel.tsx
> +      produce(measureReportLookup, async draftState => {
Make this happen in a setTimeout.

2022-09-21 14:09 UTC, hossenlopp approved these changes
Looks good!

2022-09-21 15:49 UTC, natjoe4 approved these changes
Sweet

2022-09-21 15:54 UTC, hossenlopp approved these changes
Good to go now! :)

2022-09-21 15:55 UTC, merged