Add dropdown for selecting desired populations
projecttacoma/fqm-testify pull request #45
Opened 2022-09-20 16:11 UTC by sarahmcdougall

# Summary
Allows the user to select the desired measure population(s) for each test patient.

## New Behavior
When a patient is selected, a dropdown with the label “Desired Populations” should appear.  The dropdown is populated with all the measure populations that appear in the measure bundle. When a user clicks on a measure population, it gets added to the test case state object. 

If a user clicks on a population, all of the population’s superset populations will also be selected. For example, if the numerator population is selected, then the denominator and initial population will also appear as selected values and will also get added to the test case state object.

Populations become disabled if they cannot be selected alongside the already selected populations. For example, if the user clicks on the numerator population, then the numerator exclusion population will be disabled because a patient cannot fall under both the numerator and the numerator exclusion. If the user decides to instead assign the patient to the numerator exclusion, they will need to first deselect the numerator population.

Note: Future tasking will actually use the desired populations state - this PR sets up the selection and storage in anticipation for the future tasking.

## Code Changes
* New component `utils/PopulationMultiSelect` - renders a Mantine Multiselect component. Includes functions for grabbing the measure populations off the measure bundle, keeping track of the selected populations and selecting their superset populations, and disabling populations that cannot be selected alongside already-selected populations
* Add `desiredPopulations` to the `TestCaseInfo` interface so that the desired populations for the patient to fall under can be tracked for each patient
* Add `PopulationMultiSelect` component to the `PatientInfoCard`
* Unit tests for `PatientInfoCard` and `PopulationMultiSelect`

# Testing Guidance
Run unit tests. Then, create a new test patient and test the following:
* Select the patient and select the initial population. Then, deselect the patient and select it again. Check that the initial population selection appears, showing that the desired populations state gets saved.
* Select the patient and select the denominator - check that the initial population also gets selected. This should also be the case for any other population (that when you select it, the initial population also gets selected)
    * If the denominator exclusion is available on the measure, it should be disabled.
* Select the patient and select the numerator - check that the initial population and denominator also get selected.
    * If the numerator exclusion, denominator exclusion, and/or denominator exception are available on the measure, they should be disabled.
* Select the patient and select the numerator exclusion - check that the initial population and denominator also get selected.
    * The numerator should be disabled.
* Select the patient and select the denominator exclusion - check that the initial population also gets selected
    * Everything else should be disabled.
* Select the patient and select the denominator exception - check that the initial population and denominator also get selected
    * The denominator exclusion, numerator exclusion, and numerator should be disabled. (I used the DRCommunication bundle to get access to the denominator exception for testing)

Some things to get feedback on:
* Does it make sense to disable the populations that cannot be selected with the already-selected populations? Would it be more appropriate to use the error highlighting on the multi select component instead, or maybe show a Mantine notification? Or should we get rid of the disabling altogether if we don’t want to add this checking?
* Currently, measure-population, measure-population-exclusion, and measure-observation are not included in the MultiSelect component. Should we add any handling at this time for them?
* Check that the logic for selecting/disabling measure populations aligns with the eCQM population criteria: https://build.fhir.org/ig/HL7/cqf-measures/measure-conformance.html#population-criteria

2022-09-21 14:18 UTC, mgramigna requested changes
One bug and one question

[MG1] Select a patient and click on "denominator exclusion". Only the "initial population" badge renders inside the component. I would expect "denominator exclusion to be there and not be in the dropdown list still.

[MG2] How is deleting the individual selections from the box supposed to work? Are we only allowed to delete populations that aren't the subset of another selected population? For example, if I select IPP and DENOM for a patient, when I click the delete `x` next to the chip for ipp, it switches places with denom but doesn't actually get deleted. I think ideally, deleting an individual population deletes the superset populations that it draws from? Maybe @hossenlopp has preferences on this. Regardless, we should probably avoid the need for the user to delete things in the correct order when it isn't obvious to them.

---

Plus some inline comments:

2022-09-21 14:56 UTC, sarahmcdougall commented
> [MG2] How is deleting the individual selections from the box supposed to work? Are we only allowed to delete populations that aren't the subset of another selected population? For example, if I select IPP and DENOM for a patient, when I click the delete `x` next to the chip for ipp, it switches places with denom but doesn't actually get deleted. I think ideally, deleting an individual population deletes the superset populations that it draws from? Maybe @hossenlopp has preferences on this. Regardless, we should probably avoid the need for the user to delete things in the correct order when it isn't obvious to them.

I think this is the native behavior of the MultiSelect component, so I can look into trying to override the delete functionality so that the superset populations also get deleted. I kept the native behavior because I figured the user should not be allowed to delete a superset population on its own (ex. delete the IPP but keep the numerator). That's a good point about deleting the supersets as well, since the current functionality requires a lot of clicks if the user wants to get rid of a superset population.

2022-09-21 15:06 UTC, sarahmcdougall commented on components/utils/PopulationMultiSelect.tsx
> +    const EXCLUDED_MEASURES = ['measure-population', 'measure-population-exclusion', 'measure-observation'];
yes 😶‍🌫️

2022-09-21 15:51 UTC, mgramigna commented
> > [MG2] How is deleting the individual selections from the box supposed to work? Are we only allowed to delete populations that aren't the subset of another selected population? For example, if I select IPP and DENOM for a patient, when I click the delete `x` next to the chip for ipp, it switches places with denom but doesn't actually get deleted. I think ideally, deleting an individual population deletes the superset populations that it draws from? Maybe @hossenlopp has preferences on this. Regardless, we should probably avoid the need for the user to delete things in the correct order when it isn't obvious to them.
> 
> I think this is the native behavior of the MultiSelect component, so I can look into trying to override the delete functionality so that the superset populations also get deleted. I kept the native behavior because I figured the user should not be allowed to delete a superset population on its own (ex. delete the IPP but keep the numerator). That's a good point about deleting the supersets as well, since the current functionality requires a lot of clicks if the user wants to get rid of a superset population.

Ah I see. I'd look into overriding behavior in the `onChange`, as that should trigger when an element is deleted?

2022-09-21 15:54 UTC, mgramigna commented on components/utils/PopulationMultiSelect.tsx
> +  const getMeasurePopulations = (measure: fhir4.Measure): Array<MultiSelectData> => {
Consistency nitpick haha

```suggestion
  const getMeasurePopulations = (measure: fhir4.Measure): MultiSelectData[] => {
```

2022-09-21 17:33 UTC, elsaperelli requested changes
Works great! Just two small comments :)

2022-09-21 17:33 UTC, elsaperelli commented on components/utils/PopulationMultiSelect.tsx
> +    // disable all other populations (aside from IPP) if denominator exclusion selected
When the user selects Denominator Exclusion, only the Initial Population shows up. I think in order to make sure that the Denominator Exclusion shows up, you have to disable all other populations (aside from IPP AND denominator exclusion).

![Screen Shot 2022-09-21 at 9 46 03 AM](https://user-images.githubusercontent.com/30158156/191570657-838404a3-1c7b-4531-ac32-3c4a27a1b429.png)

2022-09-21 17:54 UTC, sarahmcdougall commented on package-lock.json
> +          "integrity": "sha1-KKaq50KN0sOpLz2V8hM13SBOAzY="
The above commands didn't change it to sha512 - should I try to delete the package-lock instead?

2022-09-22 15:25 UTC, elsaperelli approved these changes
Great job! Looks good to me :)

2022-09-22 17:37 UTC, mgramigna approved these changes
nice

2022-09-22 17:37 UTC, merged