Use calculate
projecttacoma/fqm-testify pull request #64
Opened 2023-04-18 17:15 UTC by elsaperelli

# Summary

## New Behavior

## Code Changes

# Testing Guidance

2023-04-19 20:43 UTC, natjoe4 requested changes
Functionality seems unchanged to me, so great job catching all the effects of this change. Just a few smaller comments :)

2023-04-19 20:43 UTC, natjoe4 commented on components/calculation/PopulationResultsTable.tsx
> +export declare type DetailedDetailedResult = {
Also, just curious... What does `declare` do here? Haven't seen that before

2023-04-19 20:43 UTC, natjoe4 commented on components/calculation/PopulationResultsTable.tsx
> +    return PopulationResultsRow(populationResults);
The term `populationResults` is super overloaded here, consider changing the variable to `labeledPopulationResults` or something?

2023-04-20 15:18 UTC, elsaperelli commented on components/calculation/PopulationCalculation.tsx
> +import PopulationResultTable from './PopulationResultsTable';
Smooshed ✅

2023-04-20 15:19 UTC, elsaperelli commented on components/calculation/PopulationResultsTable.tsx
> +export declare type DetailedDetailedResult = {
Hahahah you mean to say `DetailedDetailedResult` doesn't look or sound good?? And actually I am also not sure- I think I may have pulled that from `ecqm-visualizers`. I think I can remove it.

2023-04-20 15:22 UTC, elsaperelli commented on components/calculation/PopulationCalculation.tsx
> +            const patientId = dr.patientId;
It probably doesn't need to be an interface then, right?

2023-04-21 18:17 UTC, natjoe4 approved these changes
Looks great! Nice work :)

2023-04-24 21:54 UTC, hossenlopp approved these changes
Excellent work!

2023-04-24 21:55 UTC, merged