Scrollable panels
projecttacoma/fqm-testify pull request #72
Opened 2023-05-30 20:36 UTC by elsaperelli

# Summary
The population comparison table and the measure highlighting in the right panel of the web application are now in two separate scrollable areas so the user can view them both at the same time.

## New Behavior
- The user can now view the population comparison table while scrolling through the measure highlighting.

## Code Changes
- `TestCaseEditor.tsx` - I put the population comparison table and the measure highlighting in different `ScrollArea`s.
- `MeasureHighlightingPanel.tsx` - Removed the `PopulationComparisonTable` from this file so that they could be in different `ScrollArea`s in `TestCaseEditor.tsx` and added the autocomplete component because we want it to scroll with the highlighting (I think).
- `PopulationComparisonTable.tsx` - Removed the autocomplete component and therefore the `defIds` parameter since it was no longer needed.
- `TestCaseEditor.test.tsx` - I got an error that the `ResizeObserver` was not defined so I just did what we do in other unit tests for `ScrollArea`s and it worked.
- `PopulationComparisonTable.test.tsx` - removed the `defIds parameter.`

# Testing Guidance
- `npm run check`
- `npm run dev`
- Try uploading different measure bundles and patients and see how it looks. Keep in mind that some of this may be improved in another in progress task through collapsible components. 
- Upload the `ratio-Encounter-reuseObservationFunction` measure bundle from the `test/integration` folder of fqm-execution. See how the multiple comparison tables look with scrolling.

2023-05-31 15:50 UTC, sarahmcdougall requested changes
A few comments in addition to the in-line comments:

1. The "info" icon contents may extend longer than the height of the population comparison table. In such a case, we can't read the entire contents of that popup. In some cases, where the population comparison table is scrollable, we can read the entire popup, but we need to scroll to do so. I think we should try to make the contents of this popup scrollable so that the user does not need to scroll on the population comparison table in order to read the entire popup. If that ends up being too tricky to implement, we can roll it into another task, but I think it should hopefully be pretty straightforward to add.
![Screenshot 2023-05-31 at 8 24 27 AM](https://github.com/projecttacoma/fqm-testify/assets/87094479/dc1ec673-4a02-4b74-9851-d3c56e5d9ebe)

2. **UPDATE: I only experience this on Safari. Everything looks fine on Chrome. Probably doesn't require any changes in this PR** 
I wanted to see if you experienced this: sometimes a horizontal scrollbar appears on the measure highlighting section, but it appears in the middle of the highlighting:
![Screenshot 2023-05-31 at 9 58 02 AM](https://github.com/projecttacoma/fqm-testify/assets/87094479/6d13b14b-ef64-4bd8-850c-13a9beb1f991)
When it appears, there's also a horizontal scrollbar at the bottom of the panel. Not sure if this is something that we can get rid of?

2023-06-01 13:51 UTC, elsaperelli commented on components/TestCaseEditor.tsx
> +          </ScrollArea>
Hmm this actually doesn't happen for me unless I have the make the window smaller than the screen...is that what was happening for you or was it the size of the screen?

2023-06-01 13:55 UTC, elsaperelli commented on components/TestCaseEditor.tsx
>                  <Grid.Col span={4}>
Good idea!

2023-06-01 15:36 UTC, elsaperelli commented
> A few comments in addition to the in-line comments:
> 
> 1. The "info" icon contents may extend longer than the height of the population comparison table. In such a case, we can't read the entire contents of that popup. In some cases, where the population comparison table is scrollable, we can read the entire popup, but we need to scroll to do so. I think we should try to make the contents of this popup scrollable so that the user does not need to scroll on the population comparison table in order to read the entire popup. If that ends up being too tricky to implement, we can roll it into another task, but I think it should hopefully be pretty straightforward to add.
>    ![Screenshot 2023-05-31 at 8 24 27 AM](https://user-images.githubusercontent.com/87094479/242332246-dc1ec673-4a02-4b74-9851-d3c56e5d9ebe.png)
> 2. **UPDATE: I only experience this on Safari. Everything looks fine on Chrome. Probably doesn't require any changes in this PR** wanted to see if you experienced this: sometimes a horizontal scrollbar appears on the measure highlighting section, but it appears in the middle of the highlighting:
>    ![Screenshot 2023-05-31 at 9 58 02 AM](https://user-images.githubusercontent.com/87094479/242333463-6d13b14b-ef64-4bd8-850c-13a9beb1f991.png)
>    When it appears, there's also a horizontal scrollbar at the bottom of the panel. Not sure if this is something that we can get rid of?

Great catch about the popover! I don't know if it's perfect, but I just made it scrollable for now. A lot of this will be cleaned up when we make these components collapsible and also when Matt does his styling overhaul, so I am not too worried about the rest for now!

2023-06-02 14:03 UTC, sarahmcdougall approved these changes
Looks good! I took a look at #73 and seems like the scrollable popover might not be needed once that PR is merged, but doesn't hurt to keep it in case we add more content to the popover in the future.

2023-06-05 19:14 UTC, lmd59 commented
Collab'd with @elsaperelli on a rebase since #73 was highly overlapping with this feature. With the collapsible, the table section does not collapse out of the way (just collapses to empty space). We may want to update functionality for the table section to have a larger max height (500px) instead of a smaller set height (250px). Then we need to make sure that the highlighting panel part of the TestCaseEditor takes up the remaining space when collapsed with something other than the current `'calc(100% - 280px)'`. We also might take a look at options for changing up the design in this section more dramatically, so we could also just ignore this issue for the moment.

2023-06-07 16:10 UTC, sarahmcdougall approved these changes
Works great! Great changes - thanks for coordinating between the different PRs!

2023-06-07 16:10 UTC, merged