Refactor existing UI/UX
projecttacoma/fqm-testify pull request #75
Opened 2023-06-08 21:47 UTC by mgramigna

# Summary

This PR makes some sweeping UI changes across the board that can loosely be categorized as follows:

1. Generally avoid use of inline `style` prop where not necessary, either by moving things out to `createStyles` or using a proper Mantine component
2. Remove some unnecessary Grid systems, and other unnecessary styles that were either doing nothing or were causing weird behavior like double scrollbars
3. Clean up the homepage and make it more responsive to all screen sizes
4. Bug fixes or misc. style changes (e.g. text emphasis, padding, etc.)

## New Behavior

* Bug fix for the patient cards now properly highlighting when selected, which they were no longer doing on `main` after #70 

No other new behavior beyond that

## Code Changes

* Yoink a lot of inline `style` to either `createStyles`, `styles`, or `sx`, which is more akin to what you should be doing in any full-fledged component library like mantine
* Replace many `div`s or `Grid`s with flexbox where appropriate
  * Also replace some misc tags with Mantine components (e.g. `<i>some text</>` to `<Text italic>some text</Text>`
* Fix error introduced by #73 which caused invalid dom nesting (button within a button)
  * To do this, I followed the official suggestion for this behavior made by the mantine docs: https://mantine.dev/core/accordion/#compose-controls
* Rework homepage spacing and layout by using specific grids and max widths on large screens
* Update tests to adhere to some wording changes in the UI 

# Testing Guidance

Test all features, test various screen sizes

2023-06-12 17:13 UTC, elsaperelli requested changes
Just one comment! Great changes!

2023-06-12 17:33 UTC, mgramigna commented on components/calculation/PopulationComparisonTableControl.tsx
> +      <Popover.Dropdown>
Yeah, I noticed this too. It's also like this on `main`, so I just didn't change that behavior 
![image](https://github.com/projecttacoma/fqm-testify/assets/16297930/a410a141-d127-4e44-ab84-4ce296e69c15)

2023-07-03 15:43 UTC, sarahmcdougall requested changes
Great changes - this really enhances the UI and the readability of our code. Just have a few suggestions

2023-07-03 15:43 UTC, sarahmcdougall commented on components/calculation/PopulationComparisonTableControl.tsx
> +          populations are compared to highlight cells green if they match and red if they don&apos;t match.
```suggestion
          populations are compared, and the cells are highlighted green if the populations match and red if they don&apos;t match.
```

2023-07-03 15:43 UTC, sarahmcdougall commented on components/calculation/PopulationComparisonTableControl.tsx
> +          For episode-based measures, the table shows patient level totals that indicate how many episodes are in each
```suggestion
          For episode-based measures, the table shows patient-level totals that indicate how many episodes are in each
```

2023-07-03 15:43 UTC, sarahmcdougall commented on components/TestCaseEditor.tsx
> +                      <CircleCheck color="green" size={40} />
Really minor suggestion here but this circle check looks pretty large compared to the size of the text - I would probably bump the size down to like 28 or 32-ish

2023-07-12 13:11 UTC, sarahmcdougall approved these changes
Great changes! 👍

2023-07-12 15:08 UTC, merged