1473 - Include clause uncoverage HTML
projecttacoma/fqm-testify pull request #90
Opened 2024-04-12 17:52 UTC by zacharyrobin

# Summary
This adds the ability to view `uncoverage` in `fqm-testify`

Jira: [TACOSTRAT-1473](https://jira.mitre.org/browse/TACOSTRAT-1473)

## New Behavior
![Screenshot 2024-04-12 at 10 34 43 AM](https://github.com/projecttacoma/fqm-testify/assets/28585306/90d13299-25ca-4efc-ba41-6a3a043ee39d)

## Code Changes

- New css file for styling 
- Main changes are in `coverage.tsx` with fancy new tabs 
- `PopulationCalculation.tsx` is also updated to send over the `groupClauseUncoverageHTML`

# Testing Guidance

~~Requires `groupClauseUncoverageHTML` from `fqm-execution`. Once the newest release for `fqm-execution` is out this shouldnt be an issue but to test in current version youll need to use [npm link](https://docs.npmjs.com/cli/v10/commands/npm-link).   Run `npm link ../fqm-execution` to link to local node module.~~

~~you can double check this worked by navigating to `/fqm-testify/node_modules/fqm-executio` and the module should look like the local `fqm-execution` directory.~~
- `npm run check`
- `npm run dev` and navigate to `http://localhost:3000`

# Additional Notes / Future Tickets

Had a discussion with @lmd59 about changing `clauseCoverageHTML` to `groupClauseCoverageHTML`. Will eventually need to add ability for `fqm-testify` to handle group clauses, could do a tab system.  I left a comment in the code with a `TODO` for future reference.

2024-04-15 17:56 UTC, elsaperelli requested changes

2024-04-15 17:56 UTC, elsaperelli commented on pages/[measureId]/coverage.tsx
> +            <Tabs.Tab value="uncoverage" /*leftSection={<IconMessageCircle style={iconStyle} />}*/>Uncoverage</Tabs.Tab>
```suggestion
            <Tabs.Tab value="coverage">Coverage</Tabs.Tab>
            <Tabs.Tab value="uncoverage">Uncoverage</Tabs.Tab>
```
I think we can delete the commented out stuff

2024-04-16 18:00 UTC, hossenlopp approved these changes
Looks good for a first pass so we can have a tool for quickly looking at the uncoverage.

2024-04-16 18:26 UTC, elsaperelli approved these changes

2024-04-16 18:26 UTC, merged