Add option to remove resources not relevant to measure
projecttacoma/fqm-testify pull request #97
Opened 2024-12-29 18:32 UTC by elsaperelli

# Summary
This PR adds an option on Patient Bundle upload to remove any resources on the Patient Bundle that are not relevant to the measure.

## New Behavior
There is now a switch on the Patient Bundle import modal that, when set, removes any resources on the Patient Bundle that do not match up with any of the Measure's data requirements. This allows the user to minimize the number of resources that are uploaded, while making sure that any necessary resources remain.

## Code Changes
- `README.md` - added sentence about removing irrelevant resources on import switch.
- `ImportModal.test.tsx` - added `mantineRecoilWrap` to the component now that it included a recoil state.
- `ImportModal.tsx` - added a Mantine switch for setting the minimize resources option and associated popover for further information.
- `PatientCreationPanel.tsx` - minimizes the resources on the test case that are uploaded if the switch is set to on.
- `resourceSwitch.ts` - atom to indicate if resources on a patient bundle are to be minimized using the data requirements of the measure.
- `dataRequirements.ts` - removed empty line in the imports
- `dataRequirementsByType.ts` - created a lookup selector object for the measure's data requirements where the key is the resource type and the attributes are `keepAll` (a boolean that defaults to false but is set to true if any of the data requirements do not have a codeFilter), `valueSets`, an array of value set urls, and `directCodes`, an array of Codings.
- `ValueSetHelper.ts` - contains two helper functions: one for getting codes and systems from a valueSet url, and one for taking a testCase, a measure bundle, and the data requirements by type lookup object and returning only the resources on the test case that are relevant to the data requirements.

# Testing Guidance
- `npm run check`
- `npm run dev`
- This is definitely a slightly challenging PR to test, as there are many different things that could go wrong. The positive is that since this is a switch, as long as the switch is set to off, the previously functionality of the app will remain.
- In order to test new functionality, a strategy I used was having this locally run and also pulling up the [testify site](https://projecttacoma.github.io/fqm-testify) and importing the same measure bundle and patient bundles and ensuring that clause coverage remains the same even if the irrelevant resources are removed.
- Try to break this! Test with a variety of different measures and test cases. The best way to see if any resources we need slipped through the cracks is to check clause coverage %. If clause coverage changes at all, that means that a resource got removed that should not have.

2024-12-31 19:06 UTC, lmd59 reviewed
There's some complex stuff happening here, so I really appreciate all of the commenting! Thanks for tackling a tricky feature!

I've left most comments inline and then have one more general user-focused comment:
Recommend using the `useRecoilState(resourceSwitchOn)` in the AppHeader to disable the measure edit button or give a warning when resources have been minimized. Or I believe we still have the original files loaded into memory, so we could re-trigger the minimization on re-calculation after uploading the new measure.

2024-12-31 19:06 UTC, lmd59 commented on util/ValueSetHelper.ts
> +                  if (matchingDRType.directCodes.length > 0) {
This set of code from line 71 to 87 is also used a lot and might benefit from being pulled out into its own function.

2024-12-31 19:06 UTC, lmd59 commented on util/ValueSetHelper.ts
> +                // example: SearchParameter
Are we planning on handling these cases?

2025-01-03 19:26 UTC, elsaperelli commented on util/ValueSetHelper.ts
> +                // example: SearchParameter
Lol good question. I am really not sure and was having a hard time with these so I was wondering if you or @hossenlopp had any more insight if this is necessary (at least for now).

2025-01-03 20:03 UTC, elsaperelli commented on state/selectors/dataRequirementsByType.ts
> +              } else if (cf.code) {
Ah gotcha sounds good, I think I can just change this to two `if` statements like it's done in `util/fhir/codes.ts`

2025-01-03 20:12 UTC, elsaperelli commented on state/selectors/dataRequirementsByType.ts
> +              dr.codeFilter.forEach(cf => {
Hm I am a little confused by this comment. Since they are ANDed together, that sounds to me like they needed to be matched up to a resource exactly...but that sounds like it would cause a lot of issues

2025-01-03 21:06 UTC, lmd59 commented on state/selectors/dataRequirementsByType.ts
> +              dr.codeFilter.forEach(cf => {
Yeah- I think that's true if we were trying to be exact. But I think we're trying to do a helpful filter with this task rather than an exact filter? I think we're essentially treating them like an OR still instead of an AND, which means we'll still definitely keeping the relevant information, but we might have had the opportunity to filter down to even less information if we did the AND.

2025-01-04 17:27 UTC, elsaperelli commented
As a temporary and somewhat simple solution to your comments regarding making it clearer to the user when the resources on a Test Case have been minimized, I decided to add an attribute to the `TestCaseInfo` interface as a `minResources` boolean. This way the boolean is set to "true" if the minimize resources option was used on Import. I decided on this approach so that the user can decide to use this option on a Test Case by Test Case basis. This also makes it easier for the user to see which test cases were uploaded with this option even if they have also added test cases without that option. The only problem with this solution is it doesn't exactly address your suggestion of being able to run turn the option on and off when the test cases are already uploaded- I think that would be a little bit more complex and in the spirit of not scope creeping too much, I decided on this approach. I am still happy to make a follow up task to do that if that would be of interest in the future. For now, let me know if this makes sense!

2025-01-04 17:31 UTC, elsaperelli commented on state/selectors/dataRequirementsByType.ts
> +              dr.codeFilter.forEach(cf => {
Ah okay, that makes sense! Will add a comment and blub to the README!

2025-01-05 23:15 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +      r.resource?.resourceType !== 'Patient'
This logic may not be necessary. It looks like `bundleToTestCase` in `util/import.ts` already takes care of filtering them out of the testCase resource list.

2025-01-05 23:31 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +                // example: SearchParameter
We can definitely skip over cases where nonsense resources are found. SearchParameter and OperationDefinition have no business in a patient bundle.

2025-01-06 00:19 UTC, hossenlopp requested changes
The JIRA task stated we should just focus on the primaryCodePath of each resource. The logic is set up well for doing this in the `minimizeTestCaseResources` function. But the logic that takes the dataRequirements and creates the nice mapping grabs all of the codeFilters on the dataRequirements, even if they are for paths other than the primaryCodePath. This could result in codes/valuesets from a codeFilter that is NOT on the primaryCodePath to later be used in the comparison against the primaryCodePath.

I think we could keep operating with primaryCodePath limitation and sort out the dataRequirements lookup function to filter the codeFilters it finds.

But it may be fairy possible to make this work with ALL paths. It would require the map of dataRequirements to have a second level mapping for each path to the possible codes or valuesets. This would also require a few more of the funny cases with the weird cardinalities to be handled in the minimizeTestCaseResources.

There also a few suggestions I have on keeping separation of concerns and avoiding duplicates.

2025-01-06 00:19 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +function checkCodesAndValueSets(
This function could be simplified to not deal with the `resource` and `newResources` at all. All this needs to do the code comparison and return a boolean if it matches or not. This would retain separation of concerns by only having the `newResources` be managed by the `minimizeTestCaseResources` function.

2025-01-06 00:19 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +      matchingDRType.directCodes.find(dc => primaryCodeValue.coding?.find(c => c.code === dc.code))
```suggestion
      matchingDRType.directCodes.find(dc => primaryCodeValue.coding?.includes(c => c.code === dc.code))
```

`includes` should be used since we only need to know about existence in the array.

2025-01-06 00:19 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +                  }
This looks like it is the same code in the `checkCodesAndValueSets` function.

2025-01-06 00:19 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +  testCase.resources.forEach(r => {
There are multiple places that `newResources.push` is called here. It feels like this could have a chance for duplicated resources, likely when there are valueSets with overlapping codes. This could be changed to using `Array.filter` with this predicate function returning `true` when ever matching code is found. This would also allow for an easy short-circuit to help speed things up.

2025-01-07 17:23 UTC, elsaperelli commented on util/ValueSetHelper.ts
> +      matchingDRType.directCodes.find(dc => primaryCodeValue.coding?.find(c => c.code === dc.code))
If I make this change, then I get a type error with the `.find` that it is in, should I change them both?

2025-01-07 17:24 UTC, elsaperelli commented on util/ValueSetHelper.ts
> +                  }
It's a little different

2025-01-07 17:29 UTC, elsaperelli commented on util/ValueSetHelper.ts
> +  testCase.resources.forEach(r => {
I am actually not totally seeing how resources could be duplicated here, can you point to a spot in the logic where that could happen?

2025-01-07 18:57 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +      matchingDRType.directCodes.find(dc => primaryCodeValue.coding?.find(c => c.code === dc.code))
Yep. Both would need to be `.includes`. and both predicates should be returning booleans.

2025-01-07 19:30 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +                  });
This is one of the places were we could end up with duplicated resources. Since the field here is a CodeableConcept[] there effectively is a list of of list of codes. There could be a situation where there are multiple codes being used to describe the same thing but using different code systems for compatibility. Many eCQM ValueSets are grouping ValueSets that have multiple code systems for representing the same thing for compatibility. So it is very likely that an Encounter could have two codes that are both in the ValueSet for a data requirement. So this logic would add that Encounter to the newResources array twice.

Switching the entire `forEach` loop over the `testCase.resources` to a `filter` and changing the logic to `return true` when we find a match would completely eliminate the chance for duplicated resources to occur. It would also us to move on to the next resource immediately when we have found one we want to keep.

2025-01-14 20:32 UTC, elsaperelli commented on util/ValueSetHelper.ts
> +      matchingDRType.directCodes.find(dc => primaryCodeValue.coding?.find(c => c.code === dc.code))
![image](https://github.com/user-attachments/assets/9fa99242-d109-4e5b-8d82-4347269a90a9)

2025-01-16 19:15 UTC, lmd59 commented
> As a temporary and somewhat simple solution to your comments regarding making it clearer to the user when the resources on a Test Case have been minimized, I decided to add an attribute to the `TestCaseInfo` interface as a `minResources` boolean. This way the boolean is set to "true" if the minimize resources option was used on Import. I decided on this approach so that the user can decide to use this option on a Test Case by Test Case basis. This also makes it easier for the user to see which test cases were uploaded with this option even if they have also added test cases without that option. The only problem with this solution is it doesn't exactly address your suggestion of being able to run turn the option on and off when the test cases are already uploaded- I think that would be a little bit more complex and in the spirit of not scope creeping too much, I decided on this approach. I am still happy to make a follow up task to do that if that would be of interest in the future. For now, let me know if this makes sense!
> 
> Addressed in: [a930691](https://github.com/projecttacoma/fqm-testify/commit/a930691be52e8b833c0d1722c0b92a18e2b51d2e)

I think this was definitely a good add, and I agree that applying the slimming after the patient is uploaded is out of scope. I still think it would be nice to put some sort of warning on the edit bundle button at the top so that the user knows that the test cases that don't have all of their original resources may not calculate properly with a new measure.
<img width="405" alt="Screenshot 2025-01-16 at 2 13 45 PM" src="https://github.com/user-attachments/assets/fd5c7587-b91d-4bcd-9347-065731bac54c" />
We could maybe do a warning modal if the user clicks this button while there are any test cases with the minResources boolean.

2025-01-17 20:29 UTC, hossenlopp commented on util/ValueSetHelper.ts
> +      matchingDRType.directCodes.find(dc => primaryCodeValue.coding?.find(c => c.code === dc.code))
```suggestion
      matchingDRType.directCodes.some(dc => primaryCodeValue.coding?.some(c => c.code === dc.code))
```

[`some`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) is actually what i was looking for this case.

2025-01-22 22:09 UTC, hossenlopp approved these changes

2025-01-23 17:00 UTC, lmd59 approved these changes
Nice! Thanks for all of the work on making this come together!

2025-01-23 21:01 UTC, hossenlopp approved these changes

2025-01-23 21:02 UTC, merged